CREATE TABLE Adequacao (ID int(10) NOT NULL AUTO_INCREMENT, Alimento varchar(255) NOT NULL, Descricao varchar(255) NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE Refeicao (ID int(10) NOT NULL AUTO_INCREMENT, Refeicao varchar(255) NOT NULL, Descricao varchar(255) NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE Suplementacao (ID int(10) NOT NULL AUTO_INCREMENT, NomeSuplemento varchar(255) NOT NULL, Sabor varchar(255) NOT NULL, Quantidade varchar(255) NOT NULL, Descricao varchar(255) NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE Dieta (ID int(10) NOT NULL AUTO_INCREMENT, TipoDieta varchar(255), Descricao varchar(255), PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE ViaAlimentacao (ID int(10) NOT NULL AUTO_INCREMENT, TipoVia varchar(255) NOT NULL, Descricao varchar(255) NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE MembroAputado (ID int(10) NOT NULL AUTO_INCREMENT, Nome varchar(255) NOT NULL, Percentual double NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE CorPele (ID int(10) NOT NULL AUTO_INCREMENT, Cor varchar(255) NOT NULL, Descricao varchar(255) NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE Nutricionista_Paciente (NutricionistaID int(10) NOT NULL, PacienteID int(10) NOT NULL, PRIMARY KEY (NutricionistaID, PacienteID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE Paciente_Endereco (PacienteID int(10) NOT NULL, EnderecoID int(10) NOT NULL, PRIMARY KEY (PacienteID, EnderecoID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE Paciente_FormularioTriagem (PacienteID int(10) NOT NULL, FormularioTriagemID int(10) NOT NULL, PRIMARY KEY (PacienteID, FormularioTriagemID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE Paciente_OrientacoesNutricionais (PacienteID int(10) NOT NULL, OrientacoesNutricionaisID int(10) NOT NULL, PRIMARY KEY (PacienteID, OrientacoesNutricionaisID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE PrescricaoDietetica_Refeicao (PrescricaoDieteticaID int(10) NOT NULL, RefeicaoID int(10) NOT NULL, PRIMARY KEY (PrescricaoDieteticaID, RefeicaoID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE Refeicao_Adequacao (RefeicaoID int(10) NOT NULL, AdequacaoID int(10) NOT NULL, PRIMARY KEY (RefeicaoID, AdequacaoID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE Refeicao_Suplementacao (RefeicaoID int(10) NOT NULL, SuplementacaoID int(10) NOT NULL, PRIMARY KEY (RefeicaoID, SuplementacaoID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE PrescricaoDietetica_Dieta (PrescricaoDieteticaID int(10) NOT NULL, DietaID int(10) NOT NULL, PRIMARY KEY (PrescricaoDieteticaID, DietaID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE PrescricaoDietetica_ViaAlimentacao (PrescricaoDieteticaID int(10) NOT NULL, ViaAlimentacaoID int(10) NOT NULL, PRIMARY KEY (PrescricaoDieteticaID, ViaAlimentacaoID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE MembroAputado_AvaliacaoAntropometrica (MembroAputadoID int(10) NOT NULL, AvaliacaoAntropometricaID int(10) NOT NULL, PRIMARY KEY (MembroAputadoID, AvaliacaoAntropometricaID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE Nutricionista (ID int(10) NOT NULL AUTO_INCREMENT, CRN varchar(255) NOT NULL UNIQUE, Coordenador tinyint(1), Senha varchar(255) NOT NULL, TelefoneCelular varchar(255), Nome varchar(255) NOT NULL, Email varchar(255) NOT NULL, Sexo varchar(255) NOT NULL, TelefoneFixo varchar(255), DataNasc date NOT NULL, CPF varchar(255) NOT NULL UNIQUE, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE OrientacoesNutricionais (ID int(10) NOT NULL AUTO_INCREMENT, NutricionistaID int(10) NOT NULL, Nome varchar(255) NOT NULL, Orientacao varchar(255) NOT NULL, Data date NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE PrescricaoDietetica (ID int(10) NOT NULL AUTO_INCREMENT, PacienteID int(10) NOT NULL, Data varchar(255) NOT NULL, MetaCalorica varchar(255) NOT NULL, MetaProteica varchar(255) NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE FormularioTriagem (ID int(10) NOT NULL AUTO_INCREMENT, NutricionistaID int(10) NOT NULL, FaixaEtaria int(10) NOT NULL, Inativo tinyint(1), Nome varchar(255) NOT NULL, DataCriacao date NOT NULL, Descricao varchar(255) NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE Endereco (ID int(10) NOT NULL AUTO_INCREMENT, Rua varchar(255) NOT NULL, CEP varchar(255) NOT NULL, Numero int(10) NOT NULL, Complemento varchar(255), Cidade varchar(255) NOT NULL, Bairro varchar(255) NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE Paciente (ID int(10) NOT NULL AUTO_INCREMENT, CorPeleID int(10) NOT NULL, Inativo tinyint(1) NOT NULL, Arquivado tinyint(1) NOT NULL, Nome varchar(255) NOT NULL, DataNasc date NOT NULL, TelefoneFixo varchar(255), TelefoneCelular varchar(255), CPF varchar(255) NOT NULL UNIQUE, Email varchar(255), Sexo varchar(255) NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE AvaliacaoAntropometrica (ID int(10) NOT NULL AUTO_INCREMENT, PacienteID int(10) NOT NULL, Altura double NOT NULL, LarguraPanturrilha double, Peso double NOT NULL, AlturaJoelho double, Acamado tinyint(1) NOT NULL, Amputado tinyint(1) NOT NULL, CbAferida double, CbClas varchar(255), Data date NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE GravidadeDoenca (ID int(10) NOT NULL AUTO_INCREMENT, FormularioTriagemID int(10) NOT NULL, Nome varchar(255) NOT NULL, Descricao varchar(255) NOT NULL, Pontuacao double NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE EstadoNutricional (ID int(10) NOT NULL AUTO_INCREMENT, FormularioTriagemID int(10) NOT NULL, Nome varchar(255) NOT NULL, Descricao varchar(255) NOT NULL, Pontuacao double NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
CREATE TABLE NivelAssistencia (ID int(10) NOT NULL AUTO_INCREMENT, FormularioTriagemID int(10) NOT NULL, Nome varchar(255) NOT NULL, Descricao varchar(255) NOT NULL, Pontuacao double NOT NULL, PRIMARY KEY (ID)) type=InnoDB CHARACTER SET UTF8;
ALTER TABLE Paciente ADD INDEX Tem7 (CorPeleID), ADD CONSTRAINT Tem7 FOREIGN KEY (CorPeleID) REFERENCES CorPele (ID);
ALTER TABLE Nutricionista_Paciente ADD INDEX Tem2 (PacienteID), ADD CONSTRAINT Tem2 FOREIGN KEY (PacienteID) REFERENCES Paciente (ID);
ALTER TABLE Nutricionista_Paciente ADD INDEX Tem (NutricionistaID), ADD CONSTRAINT Tem FOREIGN KEY (NutricionistaID) REFERENCES Nutricionista (ID);
ALTER TABLE PrescricaoDietetica_Dieta ADD INDEX Tem4 (DietaID), ADD CONSTRAINT Tem4 FOREIGN KEY (DietaID) REFERENCES Dieta (ID);
ALTER TABLE Refeicao_Suplementacao ADD INDEX Possui13 (SuplementacaoID), ADD CONSTRAINT Possui13 FOREIGN KEY (SuplementacaoID) REFERENCES Suplementacao (ID);
ALTER TABLE Refeicao_Suplementacao ADD INDEX Possui12 (RefeicaoID), ADD CONSTRAINT Possui12 FOREIGN KEY (RefeicaoID) REFERENCES Refeicao (ID);
ALTER TABLE Refeicao_Adequacao ADD INDEX Possui11 (AdequacaoID), ADD CONSTRAINT Possui11 FOREIGN KEY (AdequacaoID) REFERENCES Adequacao (ID);
ALTER TABLE Refeicao_Adequacao ADD INDEX Possui10 (RefeicaoID), ADD CONSTRAINT Possui10 FOREIGN KEY (RefeicaoID) REFERENCES Refeicao (ID);
ALTER TABLE Paciente_FormularioTriagem ADD INDEX Possui4 (FormularioTriagemID), ADD CONSTRAINT Possui4 FOREIGN KEY (FormularioTriagemID) REFERENCES FormularioTriagem (ID);
ALTER TABLE Paciente_FormularioTriagem ADD INDEX Possui3 (PacienteID), ADD CONSTRAINT Possui3 FOREIGN KEY (PacienteID) REFERENCES Paciente (ID);
ALTER TABLE Paciente_Endereco ADD INDEX Possui2 (EnderecoID), ADD CONSTRAINT Possui2 FOREIGN KEY (EnderecoID) REFERENCES Endereco (ID);
ALTER TABLE Paciente_Endereco ADD INDEX Possui (PacienteID), ADD CONSTRAINT Possui FOREIGN KEY (PacienteID) REFERENCES Paciente (ID);
ALTER TABLE PrescricaoDietetica ADD INDEX Possui5 (PacienteID), ADD CONSTRAINT Possui5 FOREIGN KEY (PacienteID) REFERENCES Paciente (ID);
ALTER TABLE FormularioTriagem ADD INDEX Pertence (NutricionistaID), ADD CONSTRAINT Pertence FOREIGN KEY (NutricionistaID) REFERENCES Nutricionista (ID);
ALTER TABLE OrientacoesNutricionais ADD INDEX Faz (NutricionistaID), ADD CONSTRAINT Faz FOREIGN KEY (NutricionistaID) REFERENCES Nutricionista (ID);
ALTER TABLE Paciente_OrientacoesNutricionais ADD INDEX Possui7 (OrientacoesNutricionaisID), ADD CONSTRAINT Possui7 FOREIGN KEY (OrientacoesNutricionaisID) REFERENCES OrientacoesNutricionais (ID);
ALTER TABLE Paciente_OrientacoesNutricionais ADD INDEX Possui6 (PacienteID), ADD CONSTRAINT Possui6 FOREIGN KEY (PacienteID) REFERENCES Paciente (ID);
ALTER TABLE PrescricaoDietetica_Dieta ADD INDEX Tem3 (PrescricaoDieteticaID), ADD CONSTRAINT Tem3 FOREIGN KEY (PrescricaoDieteticaID) REFERENCES PrescricaoDietetica (ID);
ALTER TABLE PrescricaoDietetica_Refeicao ADD INDEX Possui8 (PrescricaoDieteticaID), ADD CONSTRAINT Possui8 FOREIGN KEY (PrescricaoDieteticaID) REFERENCES PrescricaoDietetica (ID);
ALTER TABLE PrescricaoDietetica_ViaAlimentacao ADD INDEX Tem5 (PrescricaoDieteticaID), ADD CONSTRAINT Tem5 FOREIGN KEY (PrescricaoDieteticaID) REFERENCES PrescricaoDietetica (ID);
ALTER TABLE NivelAssistencia ADD INDEX Compõe (FormularioTriagemID), ADD CONSTRAINT Compõe FOREIGN KEY (FormularioTriagemID) REFERENCES FormularioTriagem (ID);
ALTER TABLE EstadoNutricional ADD INDEX Compõe2 (FormularioTriagemID), ADD CONSTRAINT Compõe2 FOREIGN KEY (FormularioTriagemID) REFERENCES FormularioTriagem (ID);
ALTER TABLE GravidadeDoenca ADD INDEX Compõe3 (FormularioTriagemID), ADD CONSTRAINT Compõe3 FOREIGN KEY (FormularioTriagemID) REFERENCES FormularioTriagem (ID);
ALTER TABLE MembroAputado_AvaliacaoAntropometrica ADD INDEX Compõe5 (AvaliacaoAntropometricaID), ADD CONSTRAINT Compõe5 FOREIGN KEY (AvaliacaoAntropometricaID) REFERENCES AvaliacaoAntropometrica (ID);
ALTER TABLE MembroAputado_AvaliacaoAntropometrica ADD INDEX Compõe4 (MembroAputadoID), ADD CONSTRAINT Compõe4 FOREIGN KEY (MembroAputadoID) REFERENCES MembroAputado (ID);
ALTER TABLE AvaliacaoAntropometrica ADD INDEX Possui14 (PacienteID), ADD CONSTRAINT Possui14 FOREIGN KEY (PacienteID) REFERENCES Paciente (ID);
ALTER TABLE PrescricaoDietetica_ViaAlimentacao ADD INDEX Tem6 (ViaAlimentacaoID), ADD CONSTRAINT Tem6 FOREIGN KEY (ViaAlimentacaoID) REFERENCES ViaAlimentacao (ID);
ALTER TABLE PrescricaoDietetica_Refeicao ADD INDEX Possui9 (RefeicaoID), ADD CONSTRAINT Possui9 FOREIGN KEY (RefeicaoID) REFERENCES Refeicao (ID);
